#!/usr/bin/env bash

pushd ..
source setup_env.sh
popd

if [ $# -le 0 ];
then
    echo "Test case is not set, using default: \"test\""
    testcases=../test
else
    testcases=$1
fi

pushd "../build" || echo "Unable to compile"
    echo "compiling..."
    ninja -j$(nproc) || exit
popd || exit

WORKDIR=$(mktemp -d -p .)

rm -rf "./dirforgdb"

mv "$WORKDIR" "dirforgdb"

WORKDIR=dirforgdb

cd "$WORKDIR" || exit
# chmod 0744 "$WORKDIR" || exit

# For RISC-V, uncomment the following line
# clang -w -S -gline-tables-only -O0 -Xclang \
#         -disable-O0-optnone -fno-builtin \
#         -target riscv32 -march=rv32imfd \
#         -mfloat-abi=hard \
#         -emit-llvm ${testcases}/*.c

clang -w -S -gline-tables-only -O0 -Xclang \
        -disable-O0-optnone -fno-builtin \
        -target arm -march=armv4t \
        -mfloat-abi=hard \
        -emit-llvm ${testcases}/*.c

# For RISC-V, uncomment the following line
# llvm-link *.ll ../libraries/riscv/builtininteger.ll \
#                    ../libraries/riscv/builtinstd.ll \
#                    -o unoptimized.ll

llvm-link *.ll ../libraries/arm/builtininteger.ll \
                   ../libraries/arm/builtinstd.ll \
                   -o unoptimized.ll

opt -S unoptimized.ll \
    -mem2reg -indvars -loop-simplify -instcombine -globaldce -dce \
    -o optimized.ll
