#!/usr/bin/env bash

if [ $# -le 0 ];
then
    echo "Test case is not set, using default: \"loopexamples/nested\""
    testcases=loopexamples/nested
else
    testcases=$1
fi

WORKDIR=$(mktemp -d -p /workspaces/llvmta/testcases)
cd "$WORKDIR" || exit

clang -w -S -gline-tables-only -O0 -Xclang \
        -disable-O0-optnone -fno-builtin \
        -target arm -march=armv4t \
        -mfloat-abi=hard \
        -emit-llvm /workspaces/llvmta/testcases/Benchmarks/"$testcases"/*.c \
        -o tmp.ll
llvm-link tmp.ll /workspaces/llvmta/testcases/libraries/arm/builtininteger.ll \
                    /workspaces/llvmta/testcases/libraries/arm/builtinstd.ll \
                    -o unoptimized.ll
opt -S unoptimized.ll \
    -mem2reg -indvars -loop-simplify -instcombine -globaldce -dce \
    -o optimized.ll

gdb -tui --args llvmta -disable-tail-calls -float-abi=hard -mattr=-neon,+vfp2 -O0 \
--ta-analysis-entry-point=main --ta-muarch-type=inorder \
--ta-memory-type=separatecaches --ta-strict=false \
--ta-loop-bounds-file=\
"/workspaces/llvmta/testcases/Benchmarks/loopexamples/nested/LoopAnnotations_Arm|NotOptimized|HardFloat.csv" \
--ta-num-callsite-tokens=1 optimized.ll

echo "to do post clean, just type:"
echo "rm -rf $WORKDIR"
exit 0